security:
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$12$xRKqHv0hM3PAYaKQLspVtuta9/WMK7Z.2hkVzCq9pZMURYnSVT3QW
                        roles: 'ROLE_ADMIN'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            http_basic: ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
