index:
    path: /
    controller: App\Controller\DefaultController::index
category:
    path: /category/{slug}
    controller: App\Controller\DefaultController::categoryAction
    requirements:
        slug: '.*'
product:
    path: /product/{slug}
    controller: App\Controller\ProductController::index
search_product:
    path: /search_product/{text}
    controller: App\Controller\ProductController::searchProduct
add_to_basket:
    path: /add_to_basket
    controller: App\Controller\DeliveryController:addToBasket
checkout:
    path: /checkout
    controller: App\Controller\DeliveryController:checkout
post_offices:
    path: /post_offices
    controller: App\Controller\DeliveryController:getPostOffices
basket_view:
    path: /basket
    controller: App\Controller\DeliveryController:basketView
header_categories:
    path: /header_categories
    controller: App\Controller\DefaultController::getHeaderCategories
sendMail:
    path: /sendMail
    controller: App\Controller\DefaultController::sendMail
admin:
    path: /adminPage
    controller: App\Controller\Admin\MainController:index
categories:
    path: /adminPage/categories
    controller: App\Controller\Admin\CategoryController:categoriesView
add_sub_category:
    path: /adminPage/add_sub_category/{id}
    controller: App\Controller\Admin\CategoryController:add_sub_category
edit_category:
    path: /adminPage/edit_category/{id}
    controller: App\Controller\Admin\CategoryController:edit_category
products:
    path: /adminPage/products
    controller: App\Controller\Admin\MainController:productsView
get_products_by_category:
    path: /adminPage/get_products_by_category/{id}
    controller: App\Controller\Admin\ProductController:getProducts
add_product:
    path: /adminPage/add_product/{id}
    controller: App\Controller\Admin\ProductController:addProduct
edit_product:
    path: /adminPage/edit_product/{id}
    controller: App\Controller\Admin\ProductController:editProduct
delete_product_image:
    path: /adminPage/delete_product_image/{id}
    controller: App\Controller\Admin\ProductController:deleteImage
brands:
    path: /adminPage/show_brands
    controller: App\Controller\Admin\BrandController:index
add_brand_ajax:
    path: /adminPage/add_brand_ajax
    controller: App\Controller\Admin\BrandController:addBrandAjax

