index:
    path: /
    controller: App\Controller\DefaultController::index
category:
    path: /category/{slug}
    controller: App\Controller\DefaultController::categoryAction
    requirements:
        slug: '.*'
product:
    path: /product/{slug}
    controller: App\Controller\ProductController::index
add_to_basket:
    path: /add_to_basket
    controller: App\Controller\DeliveryController:addToBasket
checkout:
    path: /checkout
    controller: App\Controller\DeliveryController:checkout
post_offices:
    path: /post_offices
    controller: App\Controller\DeliveryController:getPostOffices
basket_view:
    path: /basket
    controller: App\Controller\DeliveryController:basketView
header_categories:
    path: /header_categories
    controller: App\Controller\DefaultController::getHeaderCategories
admin:
    path: /adminPage
    controller: App\Controller\Admin\MainController:index
categories:
    path: /adminPage/categories
    controller: App\Controller\Admin\CategoryController:categoriesView
add_sub_category:
    path: /adminPage/add_sub_category/{id}
    controller: App\Controller\Admin\CategoryController:add_sub_category
products:
    path: /adminPage/products
    controller: App\Controller\Admin\MainController:productsView