index:
    path: /
    controller: App\Controller\DefaultController::index
category:
    path: /category/{slug}
    controller: App\Controller\DefaultController::categoryAction
    requirements:
        slug: '.*'
product:
    path: /product/{slug}
    controller: App\Controller\ProductController::index
add_to_basket:
    path: /add_to_basket
    controller: App\Controller\DeliveryController:addToBasket
checkout:
    path: /checkout
    controller: App\Controller\DeliveryController:checkout
post_offices:
    path: /post_offices
    controller: App\Controller\DeliveryController:getPostOffices
basket_view:
    path: /basket
    controller: App\Controller\DeliveryController:basketView
header_categories:
    path: /header_categories
    controller: App\Controller\DefaultController::getHeaderCategories